- arguments:
    - -XHaskell2010
- ignore: { name: "Avoid lambda" }
- ignore: { name: "Use infix" }
- ignore: { name: "Use fmap" }
- ignore: { name: "Replace case with fromMaybe" }
- ignore: { name: "Use fromMaybe" }
- ignore: { name: "Eta reduce" }
- ignore: { name: "Use guards" }
- ignore: { name: "Reduce duplication" }
