cabal-version:      2.4
name:               idc-catalog
version:            0.1.0.0
synopsis:           REST services for IDC-10 and IDC-11 catalogs
build-type:         Simple

common shared
  default-language: Haskell2010
  default-extensions:
    DataKinds
    DerivingStrategies
    FlexibleContexts
    FlexibleInstances
    GADTs
    GeneralizedNewtypeDeriving
    MultiParamTypeClasses
    OverloadedStrings
    QuasiQuotes
    ScopedTypeVariables
    StandaloneDeriving
    TemplateHaskell
    TypeFamilies
    TypeOperators
    UndecidableInstances
  ghc-options:      -Wall -Werror -hiedir dist-newstyle/hie

library
  import:           shared
  hs-source-dirs:   src
  exposed-modules:
    Idc.Api
    Idc.App
    Idc.Cache
    Idc.Config
    Idc.Import
    Idc.Migrate
    Idc.Problem
    Idc.Models
    Idc.Search
  build-depends:
    , aeson
    , base
    , bytestring
    , containers
    , esqueleto
    , filepath
    , insert-ordered-containers
    , monad-logger
    , persistent
    , persistent-postgresql
    , resource-pool
    , resourcet
    , servant
    , servant-server
    , servant-swagger
    , swagger2
    , text
    , time
    , transformers
    , warp

executable idc-catalog
  import:           shared
  hs-source-dirs:   app
  main-is:          Main.hs
  build-depends:
    , base
    , idc-catalog
    , servant-server
    , text
    , wai
    , warp

test-suite idc-catalog-test
  import:           shared
  type:             exitcode-stdio-1.0
  hs-source-dirs:   test
  main-is:          Spec.hs
  other-modules:
    Idc.ImportSpec
    Idc.ProblemSpec
    Idc.SearchSpec
  build-depends:
    , aeson
    , base
    , containers
    , hspec
    , idc-catalog
    , QuickCheck
    , text
